### ISSUE TITLE
Feature Request: Use different AD attributes for PPSK attributes

### ISSUE THREAD

**Issue by rmoore3** [ExtremeNetworksSA/XIQ-AD-User-Sync#1]
I would like the ability to use a different AD attribute for createPPSKuser  "name" and "user_name". Curranty it uses the AD attribute "name". Could you make it to allow the use of other AD attributes such as "SAMAccountName" which is already gathered in the Ldap lookup?

Thanks!

**Comment by timjsmith24** [comment]
This was something that was decided against as most customers wanted to go off of the users name instead of AD Account name. But, if you wanted to leverage this, you could make these changes to the script.

Changes to make
line 137 - def createPPSKuser(name,user_name, mail, usergroupID):
line 140 - payload = json.dumps({"user_group_id": usergroupID ,"name": name,"user_name": name,"password": "", "email_address": mail, "email_password_delivery": mail})
line 354 - if not any(d['user_name'] == details['username'] for d in ppsk_users) and not any(d == details['userAccountControl'] for d in ldap_disable_codes):
line 356 - user_created = createPPSKuser(name, details['username'], details["email"], details['xiq_role'])

These 4 lines would use the SAMAccountName as the username for PPSK while preserving the name of the user. Just so you know, if you've already synced users, the script will not remove them as it checks to remove based on email address. So you may want to remove users from the PPSK group first.

reach out if you have any questions or would like me to send you an updated script in zip folder - tismith@extremenetworks.com
